import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { AuthUserProvider } from "./auth";
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";
import "material-symbols";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Deep's Blog",
  description: "Generated by Deep's coding skills",
};


export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <AuthUserProvider>
        <body className={`${inter.className} min-h-screen`}>
          <Navbar />
          {children}
          <Footer />
        </body>
      </AuthUserProvider>
    </html>
  );
}
