import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { AuthUserProvider } from "./auth";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Deep's Blog",
  description: "Generated by Deep's coding skills",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <AuthUserProvider>
        <body className={inter.className}>{children}</body>
      </AuthUserProvider>
    </html>
  );
}
